# Generated by Django 2.2 on 2020-12-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodname', models.CharField(max_length=255)),
                ('prodprice', models.FloatField()),
                ('prodimage', models.ImageField(upload_to='uploads/')),
                ('prodimage1', models.ImageField(upload_to='uploads/')),
                ('proddesc', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
